class ConfigurationPageConstants:
    CONFIGURATION_READY_ANSWER = '(//*[contains(text(), "Готові відповіді")])[1]'
    SAVE_BUTTON_CONFIGURATION = '//*[@class="cft-button__text"]'
    MESSAGE_SUCCESSFULLY_SAVE = '//*[@class="cft-flash-message__content"]'
    ADD_ANSWER_BUTTON = '//*[contains(text(), "Додати відповідь")]'
    FIELD_NAME = '//*[@class="cft-input__field" and @name="title"]'
    FIELD_TEXT_MESSAGE = '//*[@class="cft-input__field" and @name="text"]'
    NEW_READY_ANSWER = '//*[@class="cft-template-actions__item cft-template-actions__item_type_name"]'
    USER_AVATAR_XPATH = '//img[@data-toggle="dropdown"]'
    LOGOUT_XPATH = '//a[@href="https://crafta.ua/uk/auth/logout" and contains(text(), "Вихід")]'
    DELETE_ANSWER_XPATH = '(//*[@type="submit" and contains(text(), "Видалити")])[1]'
    VERIFY_SUCCESSFULLY_MESSAGE = '//div[@class="cft-flash-message__content"]'
